#  This workflow is an automated CD to the DockerHub.
#  The auto-trigger is disabled by default, you can edit the trigger in the `on` section if you want.

name: Publish to Docker Hub

on:
  workflow_dispatch:

#  Uncomment the following line to trigger the workflow for `push` events on the `master` branch
#  push:
#    branches:
#       - master

jobs:
  dockerhub-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Clean up space for action
        run: rm -rf /opt/hostedtoolcache

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          #  Register your DockerHub username and password in the repository's GA secrets.
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          #  Update with your image name
          tags: ${{ secrets.DOCKER_USERNAME }}/image-name:latest

      - name: Log out of Docker Hub
        run: docker logout

